model_config:
  name: Qwen/Qwen3-32B
  batch_size: 1024
  rope_scaling:
    rope_type: yarn
    factor: 4.0
    original_max_position_embeddings: 32768
  sampling_params:
    n: 1
    max_tokens: 2000
    top_p: 0.8
    top_k: 20
    temperature: 0.7
  enable_thinking: false
rag_config:
  rag_type: mongodb_gt
  data_path: dataset/wildchat_aqa_sampled_subset_with_embedding_and_gpt_generated_query
  max_context_token_count: 127000
  topk: 5
  prompt_template_path: prompts/eval_wildchat_aqa_prompt_use_summary_rank.md
  mongodb_host_name: localhost:27017
  doc_field_name: document_summary
