#!/bin/bash

export PATH="$HOME/bin:$PATH"
export PYTHONPATH=$PYTHONPATH:$(pwd)
# export ELASTIC_PASSWORD=<YOUR_ELASTIC_PASSWORD>
# export OPENAI_API_KEY=<YOUR_OPENAI_API_KEY>
# export HF_TOKEN=<YOUR_HF_TOKEN>
# export WANDB_API_KEY=<YOUR_WANDB_API_KEY>