model_config:
  name: o4-mini
  batch_size: 2000
  request_mode: offline_batch
  rpm_limit: 500
  tpm_limit: 200000
  sampling_params:
    response_format:
      type: json_object
rag_config:
  rag_type: none
  data_path: dataset/wildchat_aqa_sampled_subset
  max_context_token_count: 195000
  prompt_template_path: prompts/eval_wildchat_aqa_prompt_no_context_rank.md
